@extends('_layouts/light')

@push('head')
<title>{{$page['title']}}|{{$page['sub_title']}}</title>
<meta property="fb:app_id"             content="<?= ff\config('app_id');?>"/>
<meta property="og:type" content="website" />
<meta property="og:title" content="{{$page['title']}}|{{$page['sub_title']}}" />
<meta property="og:image" content="{{$page['photo']}}" />
<meta property="og:url" content="{{route('animations.index')}}" />
<meta property="og:site_name" name="application-name" content="GetEz-簡單新生活"/>
<meta property="og:updated_time" content="{!!$animation->updated_at_iso!!}" />
<link href="https://fonts.googleapis.com/css?family=Fruktur" rel="stylesheet">
<meta http-equiv="last-modified" content="{!!$animation->updated_at_iso!!}" />
<meta itemprop="dateModified" content="{!!$animation->updated_at_iso!!}"/>
<meta itemprop="datePublished" content="{!!$animation->created_at_iso!!}">
<meta itemprop="dateCreated" content="{!!$animation->created_at_iso!!}"/>
<!-- Open Graph Meta Tags generated by MashShare 3.3.4 - https://www.mashshare.net -->
<!-- This site is optimized with the Yoast SEO plugin v3.7.1 - https://yoast.com/wordpress/plugins/seo/ -->
<link rel="canonical" href="{{see_also(Request::url())}}" />
<link rel="stylesheet" href="{{('/css/animations.css')}}?v=4">

@endpush
@include("animations.ad")
@section('content')

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container animation-logo">
            <div class="navbar-header">

                <a href="{{route('animations.index',[],false)}}" id="logo">
                    <span class="logo-text"> getEz !!</span>
                </a>

            </div>

        </div>
    </nav>

    <div class="  col-lg-offset-1 col-lg-10   margin-top-80 col-sm-12 padding-0">

        <article class="col-lg-9 tabs-area " id="content">
            @if($mobile==true)
                <div class="ad-m" >{!!get_adCode(7,$plan,'animation')!!}</div>
            @endif

            <header>
                <h1 itemprop="headline">
                    {{$animation->title}}
                </h1>
            </header>

                        <!--文章內容----------------->
                <div class="article-content" itemprop="articleBody">
                    @foreach ($animations as $k=> $animation)
                        <div class="col-lg-4" onclick="location.href('{{route('animations.show',['id'=>$animation->id],false)}}')">

                           <a href="{{route('animations.show',['id'=>$animation->id],false)}}"> <img  class="img img-responsive img-fix-height" src="/animation_photos/{{$animation->photo}}"></a>
                            <div class="animation-title" ><a href="{{route('animations.show',['id'=>$animation->id],false)}}">{{$animation->title}}</a></div>
                        </div>
                    @endforeach
                       {!! show_page_bar_scroll($animations, 'btn-success btn-lg')!!}

                    <p>&nbsp;</p>
                </div>

        </article>

        <section align="center" class="col-lg-3 section-right" >
            @if($mobile==false)
                <div class="ad-long" style="text-align: left">{!!get_adCode(4,$plan,'animation')!!}</div>
            @endif

        </section>
    </div>

@endsection
@push('scripts')

<script>
    window.fbAsyncInit = function () {
        FB.init({
            appId: '<?= ff\config('app_id');?>',
            xfbml: true,
            version: 'v2.5'
        });
    };

    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/zh_TW/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

</script>


@endpush