@extends('_layouts/light')

@push('head')
<title>{{$animation->title}}</title>
<meta property="fb:app_id"             content="<?= ff\config('app_id');?>"/>
<meta property="og:type" content="website" />
<meta property="og:title" content="{{$animation->title}}" />
<meta property="og:image" content="{{$animation->og_url}}" />
<meta property="og:url" content="{{$animation->og_url}}" />
<meta property="og:site_name" name="application-name" content="GetEz-簡單新生活"/>
@if (Route::currentRouteName()=='animations.show'and isset($animation->author->fb_page)  and  $animation->author->fb_page!='')
    <meta property="article:publisher" content="https://www.facebook.com/{!!$animation->author->fb_page!!}">
@endif
@if (Route::currentRouteName()=='animations.show'  and isset($animation->author->fb_page) and  $animation->author->fb_page!='')
    <meta property="article:author" content="https://www.facebook.com/{!!$animation->author->fb_page!!}">
@endif
<meta property="og:updated_time" content="{!!$animation->updated_at_iso!!}" />
<link href="https://fonts.googleapis.com/css?family=Fruktur" rel="stylesheet">
<meta http-equiv="last-modified" content="{!!$animation->updated_at_iso!!}" />
<meta itemprop="dateModified" content="{!!$animation->updated_at_iso!!}"/>
<meta itemprop="datePublished" content="{!!$animation->created_at_iso!!}">
<meta itemprop="dateCreated" content="{!!$animation->created_at_iso!!}"/>
<!-- Open Graph Meta Tags generated by MashShare 3.3.4 - https://www.mashshare.net -->
<!-- This site is optimized with the Yoast SEO plugin v3.7.1 - https://yoast.com/wordpress/plugins/seo/ -->
<link rel="canonical" href="{{see_also(Request::url())}}" />
<link rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{{('/css/AdminLTE.min.css')}}">
<link rel="stylesheet" href="{{('/css/animations.css')}}?v=9">

@endpush

@section('content')

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container animation-logo">
            <div class="navbar-header">

                <a href="{{route('animations.index',[],false)}}" id="logo">
                    <span class="logo-text"> getEz !!</span>
                </a>

            </div>

        </div>
    </nav>
    <div class="  col-lg-offset-2 col-lg-9  col-sm-12 margin-top-80 padding-0">

        <article class="col-lg-8 tabs-area " id="content">


            <header>
                <h1 itemprop="headline">
                    {{$animation->title}}
                </h1>
            </header>
            @if($mobile==false)
            <div class="ad-l">{!!get_adCode(1,$plan,'animation')!!}</div>
            @else
                <div class="ad-m">{!!get_adCode(5,$plan,'animation')!!}</div>
            @endif
            <!--文章內容----------------->

                <div class="article-content" itemprop="articleBody">
                <div class="row" style="width:85%;margin: 0 auto;margin-bottom: 15px">
                    <div class="col-xs-2 ">

                        <a class="btn bg-light-blue btn-block btn-share"
                           href="https://www.facebook.com/sharer/sharer.php?u={!!rawurldecode($page['share_url'])!!}&description={!!rawurldecode($page['sub_title'])!!}"
                           target="_blank" alt="Facebook">
                            <i class="fa fa-facebook " id="fb_share" ></i> <span class="share_btn">分享</span>
                        </a>
                    </div>
                    <div class="col-xs-2">
                        <a class="btn bg-red btn-block btn-share"
                           href="https://plus.google.com/share?url={!!rawurldecode($page['share_url'])!!}&t={!!rawurldecode($page['sub_title'])!!}"
                           target="_blank">
                            <i class="fa fa-google-plus "></i><span class="share_btn">分享</span></a>
                    </div>
                    <div class="col-xs-2">
                        <a class="btn bg-aqua btn-block btn-share"
                           href="https://twitter.com/intent/tweet?url={!!rawurldecode($page['share_url'])!!}&text={!!rawurldecode($page['sub_title'])!!}"
                           target="_blank">
                            <i class="fa fa-twitter"></i><span class="share_btn">分享</span></a>
                    </div>
                    <div class="col-xs-2">
                        <a class="btn btn-block btn-share" style="background-color: rgb(210,87,47) ;color:white "
                           href="https://www.plurk.com/?qualifier=shares&status={!!rawurldecode($page['share_url'])!!}"
                           target="_blank">
                            <strong style="font-family: Noto Sans CJK JP Black">P</strong> <span class="share_btn">&nbsp;分享</span></a>
                    </div>


                    <div class="col-lg-2 col-xs-5 " >
                        <script src="https://apis.google.com/js/platform.js" async defer></script>
                        <g:plusone></g:plusone></div>
                    <div class="fb-like col-lg-2 col-xs-4" data-layout="button_count" data-href="{!!($page['share_url'])!!}"  ></div>

                </div>

                    <img class="img img-responsive" src="/animation_photos/{{$animation->photo}}">

                </div>

                <aside class="comments comments_show" style="padding-bottom:5px " id="comments">

                    <article class="fb-comments" data-href="{{$page['share_url']}}" data-numposts="5"
                             data-width="100%">
                    </article>

                </aside>
            @if($mobile==false)
                <div class="ad-l">{!!get_adCode(2,$plan,'animation')!!}</div>
            @else
               <div class="ad-m">{!!get_adCode(6,$plan,'animation')!!}</div>
            @endif
        </article>
        <section align="center" class="col-lg-4 section-right" >
            @if($mobile==false)
                <div class="ad-long" style="text-align: left">{!!get_adCode(3,$plan,'animation')!!}</div>
            @endif

                @foreach ($rand as $a=>$rand_animation)
                    <div class="img-rand-div">

                        <a href="{{route('animations.show',['id'=>$rand_animation->id],false)}}"><img  class="img img-responsive img-rand" src="/animation_photos/{{$rand_animation->photo}}"></a>
                        <a href="{{route('animations.show',['id'=>$rand_animation->id],false)}}"><p>{{$rand_animation->title}}</p></a>
                    </div>
                @endforeach


        </section>
    </div>
    @include("animations.ad")
@endsection
@push('scripts')
<script>
    window.fbAsyncInit = function () {
        FB.init({
            appId: '<?= ff\config('app_id');?>',
            xfbml: true,
            version: 'v2.5'
        });
    };

    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/zh_TW/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

</script>
@endpush